Caricare in un dataframe Pandas la collection "sales" del database "sample_supplies" che si pu√≤ recuperare tramite la stringa di connessione

"mongodb://webUser:xxx123xxx@cluster0-shard-00-00.algwo.mongodb.net:27017,cluster0-shard-00-01.algwo.mongodb.net:27017,cluster0-shard-00-02.algwo.mongodb.net:27017/?ssl=true&replicaSet=atlas-am4cb3-shard-0&authSource=admin&retryWrites=true&w=majority"

**Una volta caricata la collection nel dataframe pandas, scrivere il codice necessario per inserire i record del dataframe in una collection presente nel proprio database. Chiamare la nuova collection "vendite".**

**A questo punto scrivere le istruzioni per:**

In [ ]:
import pymongo
import pandas as pd

In [ ]:
'''client = pymongo.MongoClient("mongodb://Emanuele-Visioli:EMAnuele25102004@cluster0-shard-00-00.x7fma.mongodb.net:27017,cluster0-shard-00-01.x7fma.mongodb.net:27017,cluster0-shard-00-02.x7fma.mongodb.net:27017/myFirstDatabase?ssl=true&replicaSet=atlas-566dc8-shard-0&authSource=admin&retryWrites=true&w=majority")
db = client.sample_supplies'''

'client = pymongo.MongoClient("mongodb://Emanuele-Visioli:EMAnuele25102004@cluster0-shard-00-00.x7fma.mongodb.net:27017,cluster0-shard-00-01.x7fma.mongodb.net:27017,cluster0-shard-00-02.x7fma.mongodb.net:27017/myFirstDatabase?ssl=true&replicaSet=atlas-566dc8-shard-0&authSource=admin&retryWrites=true&w=majority")\ndb = client.sample_supplies'

In [ ]:
'''result=db.sales.find_one()
result'''

'result=db.sales.find_one()\nresult'

In [ ]:
'''df=pd.DataFrame(list(db.sales.find()))
df'''

'df=pd.DataFrame(list(db.sales.find()))\ndf'

----------------------------------

In [ ]:
client = pymongo.MongoClient("mongodb://Livera2003:Waduge78&@cluster0-shard-00-00.uylmr.mongodb.net:27017,cluster0-shard-00-01.uylmr.mongodb.net:27017,cluster0-shard-00-02.uylmr.mongodb.net:27017/myFirstDatabase?ssl=true&replicaSet=atlas-38dmxu-shard-0&authSource=admin&retryWrites=true&w=majority")
db2 = client.Livera1

In [ ]:
'''db2.vendite_lv.insert_many(df.to_dict('records'))'''

"db2.vendite_lv.insert_many(df.to_dict('records'))"

In [ ]:
df = pd.DataFrame(list(db2.vendite_lv.find()))

In [ ]:
df

,_id,saleDate,items,storeLocation,customer,couponUsed,purchaseMethod
0,5bd761dcae323e45a93ccfe8,2015-03-23 21:06:49.506,"[{'name': 'notepad', 'tags': None, 'price': 35...",Denver,"{'gender': 'M', 'age': 50, 'email': 'cauho@wit...",True,Online
1,5bd761dcae323e45a93ccfe9,2015-08-25 10:01:02.918,"[{'name': 'binder', 'tags': None, 'price': 28....",Seattle,"{'gender': 'M', 'age': 58, 'email': 'keecade@h...",False,Phone
2,5bd761dcae323e45a93ccfea,2017-06-22 09:54:14.185,"[{'name': 'notepad', 'tags': None, 'price': 30...",Denver,"{'gender': 'M', 'age': 59, 'email': 'worbiduh@...",False,In store
3,5bd761dcae323e45a93ccfeb,2015-02-23 09:53:59.343,"[{'name': 'binder', 'tags': None, 'price': 20....",Seattle,"{'gender': 'F', 'age': 53, 'email': 'vatires@t...",False,In store
4,5bd761dcae323e45a93ccfec,2017-12-03 18:39:48.253,"[{'name': 'backpack', 'tags': None, 'price': 1...",London,"{'gender': 'M', 'age': 48, 'email': 'dotzu@ib....",False,In store
...,...,...,...,...,...,...,...
3639,5bd761deae323e45a93ce36a,2013-10-06 22:39:37.868,"[{'name': 'binder', 'tags': None, 'price': 13....",Denver,"{'gender': 'F', 'age': 70, 'email': 'opujuw@ab...",False,In store
3640,5bd761deae323e45a93ce36b,2016-01-20 17:29:10.225,"[{'name': 'binder', 'tags': None, 'price': 28....",Austin,"{'gender': 'F', 'age': 53, 'email': 'du@rum.py...",False,In store
3641,5bd761deae323e45a93ce36c,2014-11-29 10:09:41.573,"[{'name': 'binder', 'tags': None, 'price': 13....",Denver,"{'gender': 'F', 'age': 55, 'email': 'dup@katje...",False,In store
3642,5bd761deae323e45a93ce36e,2013-12-07 11:06:25.510,"[{'name': 'notepad', 'tags': None, 'price': 33...",Denver,"{'gender': 'M', 'age': 67, 'email': 'hu@pehabu...",False,Online
3643,5bd761deae323e45a93ce36f,2014-08-18 06:25:49.739,"[{'name': 'binder', 'tags': None, 'price': 29....",New York,"{'gender': 'M', 'age': 41, 'email': 'lihzodud@...",False,Online

-------------------------------------------

**1. cancellare tutti i document relativi al negozio di San Diego**

In [ ]:
result = db2.vendite_lv.delete_many({"storeLocation":'San Diego'})
result.deleted_count

0

In [ ]:
df1 = pd.DataFrame(list(db2.vendite_lv.find()))
df1

,_id,saleDate,items,storeLocation,customer,couponUsed,purchaseMethod
0,5bd761dcae323e45a93ccfe8,2015-03-23 21:06:49.506,"[{'name': 'notepad', 'tags': None, 'price': 35...",Denver,"{'gender': 'M', 'age': 50, 'email': 'cauho@wit...",True,Online
1,5bd761dcae323e45a93ccfe9,2015-08-25 10:01:02.918,"[{'name': 'binder', 'tags': None, 'price': 28....",Seattle,"{'gender': 'M', 'age': 58, 'email': 'keecade@h...",False,Phone
2,5bd761dcae323e45a93ccfea,2017-06-22 09:54:14.185,"[{'name': 'notepad', 'tags': None, 'price': 30...",Denver,"{'gender': 'M', 'age': 59, 'email': 'worbiduh@...",False,In store
3,5bd761dcae323e45a93ccfeb,2015-02-23 09:53:59.343,"[{'name': 'binder', 'tags': None, 'price': 20....",Seattle,"{'gender': 'F', 'age': 53, 'email': 'vatires@t...",False,In store
4,5bd761dcae323e45a93ccfec,2017-12-03 18:39:48.253,"[{'name': 'backpack', 'tags': None, 'price': 1...",London,"{'gender': 'M', 'age': 48, 'email': 'dotzu@ib....",False,In store
...,...,...,...,...,...,...,...
3639,5bd761deae323e45a93ce36a,2013-10-06 22:39:37.868,"[{'name': 'binder', 'tags': None, 'price': 13....",Denver,"{'gender': 'F', 'age': 70, 'email': 'opujuw@ab...",False,In store
3640,5bd761deae323e45a93ce36b,2016-01-20 17:29:10.225,"[{'name': 'binder', 'tags': None, 'price': 28....",Austin,"{'gender': 'F', 'age': 53, 'email': 'du@rum.py...",False,In store
3641,5bd761deae323e45a93ce36c,2014-11-29 10:09:41.573,"[{'name': 'binder', 'tags': None, 'price': 13....",Denver,"{'gender': 'F', 'age': 55, 'email': 'dup@katje...",False,In store
3642,5bd761deae323e45a93ce36e,2013-12-07 11:06:25.510,"[{'name': 'notepad', 'tags': None, 'price': 33...",Denver,"{'gender': 'M', 'age': 67, 'email': 'hu@pehabu...",False,Online
3643,5bd761deae323e45a93ce36f,2014-08-18 06:25:49.739,"[{'name': 'binder', 'tags': None, 'price': 29....",New York,"{'gender': 'M', 'age': 41, 'email': 'lihzodud@...",False,Online

**2. invecchiare i clienti di 8 anni**

In [ ]:
result = db2.vendite_lv.update_many({},{ "$inc": { "customer.age": 8}})
result.modified_count

3644

In [ ]:
df1 = pd.DataFrame(list(db2.vendite_lv.find()))
df1

**3. cancellare tutti i tag 'stationary'**

In [ ]:
result = db2.vendite_lv.find({"items.tags": "stationary"})
df = pd.DataFrame(list(result))
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
result = db2.vendite_lv.update_many({},{"$pull" : {"items" :{ "tags": "stationary"}}})
result.modified_count

0

**4. eliminare tutti i document di clienti che hanno pi√π di 80 anni e meno di 40**

In [ ]:
result = db2.vendite_lv.find({'$or': [{"customer.age" : {'$gt' : 80 }} , {"customer.age" : {'$lt' : 40 }}]})
df = pd.DataFrame(list(result))
df

,_id,saleDate,items,storeLocation,customer,couponUsed,purchaseMethod
0,5bd761dcae323e45a93ccfef,2014-03-31 16:02:06.624,"[{'name': 'notepad', 'tags': None, 'price': 5....",Austin,"{'gender': 'M', 'age': 87, 'email': None, 'sat...",False,Online
1,5bd761dcae323e45a93cd004,2017-07-13 07:13:43.675,"[{'name': 'binder', 'tags': None, 'price': 21....",Denver,"{'gender': 'F', 'age': 86, 'email': 'wuulabeb@...",False,In store
2,5bd761dcae323e45a93cd00a,2015-03-30 06:59:05.365,"[{'name': 'notepad', 'tags': None, 'price': 34...",Denver,"{'gender': 'M', 'age': 82, 'email': 'henbaw@da...",False,Online
3,5bd761dcae323e45a93cd00f,2016-04-27 08:09:58.703,"[{'name': 'binder', 'tags': None, 'price': 10....",London,"{'gender': 'M', 'age': 86, 'email': 'nupettum@...",False,In store
4,5bd761dcae323e45a93cd018,2017-09-28 08:35:45.703,"[{'name': 'laptop', 'tags': None, 'price': 153...",London,"{'gender': 'M', 'age': 87, 'email': 'ep@jedofi...",False,Online
...,...,...,...,...,...,...,...
372,5bd761deae323e45a93ce30f,2015-01-31 04:13:41.858,"[{'name': 'binder', 'tags': None, 'price': 13....",Denver,"{'gender': 'M', 'age': 81, 'email': 'pe@otebi....",False,In store
373,5bd761deae323e45a93ce32b,2013-08-19 08:24:27.160,"[{'name': 'laptop', 'tags': None, 'price': 760...",Denver,"{'gender': 'F', 'age': 82, 'email': 'do@kin.md...",False,Online
374,5bd761deae323e45a93ce33d,2014-06-19 13:35:21.154,"[{'name': 'backpack', 'tags': None, 'price': 1...",New York,"{'gender': 'M', 'age': 81, 'email': 'maro@lijh...",False,In store
375,5bd761deae323e45a93ce34d,2016-02-10 04:28:30.217,"[{'name': 'notepad', 'tags': None, 'price': 29...",Austin,"{'gender': 'F', 'age': 85, 'email': 'muesusog@...",False,Online
376,5bd761deae323e45a93ce368,2015-04-22 08:31:40.113,"[{'name': 'binder', 'tags': None, 'price': 14....",New York,"{'gender': 'F', 'age': 81, 'email': 'cas@ejubu...",False,Online

In [ ]:
result = db2.vendite_lv.delete_many({'$or': [{"customer.age" : {'$gt' : 80 }} , {"customer.age" : {'$lt' : 40 }}]})
result.deleted_count

377

**5. calcolare il prezzo medio degli items**

In [ ]:
result = db2.vendite_lv.aggregate([{"$unwind": "$items"},
                                  {"$group": {"_id": "prezzo medio", "prezzoMedio": {"$avg":"$items.price"}}}])

df = pd.DataFrame(list(result))
df

            _id                          prezzoMedio
0  prezzo medio  172.5136806610942249240121580547112

**6. modificare le mail che hanno il dominio .mz in .com**

In [ ]:
result = db2.vendite_lv.find({"customer.email" : {'$regex' : ".mz$" }})
df = pd.DataFrame(list(result))
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
result = db2.vendite_lv.update_many({ "customer.email": { "$regex": ".mz$" } },
                                  [{"$set": { "customer.email": {"$replaceOne": { "input": "$email", "find": ".mz", "replacement": ".com" }}}}])
result.modified_count

0

**7. modificare il tag 'school' in 'education'**

In [ ]:
result = db2.vendite_lv.find({ "items.tags": { "$regex": "school" } })
df1 = pd.DataFrame(list(result))
df1

Empty DataFrame
Columns: []
Index: []

In [ ]:
result = db2.vendite_lv.update_many({ "items.tags": { "$regex": "school" } },
                                 [{"$set": { "items.tags": {"$replaceOne": { "input": "$tags", "find": "school", "replacement": "education" }}}}])
result.modified_count

0

**8. aggiungere 7 anni alla data degli ordini**

In [ ]:
import datetime

In [ ]:
result=db.sales_da_modificare.aggregate([
   {
      "$addFields": {
         "dateModificate": {
            "$dateFromParts": {
               "year": { "$add": [{ "$year": "$saleDate" }, 7] },
               "month": { "$month": "$saleDate" },
               "day": { "$dayOfMonth": "$saleDate" },
               "hour": { "$hour": "$saleDate" },
               "minute": { "$minute": "$saleDate" },
               "second": { "$second": "$saleDate" },
               "millisecond": { "$millisecond": "$saleDate" }
            }
         }
      }
   }
])
df1 = pd.DataFrame(list(result))
df1

3267

**9. trovare il prodotto venduto pi√π costoso**

In [ ]:
result=db.sales.find({"customer.email":"cauho@witwuta.sv"})
df=pd.DataFrame(list(result))
df

In [ ]:
result = db.sales_da_modificare.aggregate([
    { "$group": {
        "_id": "l'√®t√† massima √® ",
        "maxAge": {
            "$max": "$customer.age"
        },
        "customerdata": {
            "$push": {
                "age": "$customer.age",
                "email": "$customer.email",       
            }
        }
       }
    },
{
    '$unwind': '$customerdata'
},{
    "$match" : {"$expr": {"$eq":["$customerdata.age","$maxAge"]}}
}

    ])
dbRes = pd.DataFrame(list(result))
dbRes

**10. eliminare dagli ordini tutti i prodotti "envelopes"**

In [ ]:
result = db.sales_da_modificare.update_many({}, {'$pull': { 'items': {'name': "envelopes"}}})
result.modified_count

**11. copiare la collection "vendite" nella collection "vendite_modificata"**

**12. eliminare la collection "vendite"**

In [ ]:
'''import pymongo

str_conn = "mongodb://Livera2003:Waduge78&@cluster0-shard-00-00.uylmr.mongodb.net:27017,cluster0-shard-00-01.uylmr.mongodb.net:27017,cluster0-shard-00-02.uylmr.mongodb.net:27017/myFirstDatabase?ssl=true&replicaSet=atlas-38dmxu-shard-0&authSource=admin&retryWrites=true&w=majority"
client = pymongo.MongoClient("mongodb://Livera2003:Waduge78&@cluster0-shard-00-00.uylmr.mongodb.net:27017,cluster0-shard-00-01.uylmr.mongodb.net:27017,cluster0-shard-00-02.uylmr.mongodb.net:27017/myFirstDatabase?ssl=true&replicaSet=atlas-38dmxu-shard-0&authSource=admin&retryWrites=true&w=majority")
db = client.Livera1
collection = db.vendite_lv
collection.delete_many({})  
print(collection.count_documents({}))'''

'import pymongo\n\nstr_conn = "mongodb://Livera2003:Waduge78&@cluster0-shard-00-00.uylmr.mongodb.net:27017,cluster0-shard-00-01.uylmr.mongodb.net:27017,cluster0-shard-00-02.uylmr.mongodb.net:27017/myFirstDatabase?ssl=true&replicaSet=atlas-38dmxu-shard-0&authSource=admin&retryWrites=true&w=majority"\nclient = pymongo.MongoClient("mongodb://Livera2003:Waduge78&@cluster0-shard-00-00.uylmr.mongodb.net:27017,cluster0-shard-00-01.uylmr.mongodb.net:27017,cluster0-shard-00-02.uylmr.mongodb.net:27017/myFirstDatabase?ssl=true&replicaSet=atlas-38dmxu-shard-0&authSource=admin&retryWrites=true&w=majority")\ndb = client.Livera1\ncollection = db.vendite_lv\ncollection.delete_many({})  \nprint(collection.count_documents({}))'